### ISSUE TITLE
Proposal: new data format

### ISSUE THREAD

**Issue by iamvery** [iamvery/ratchet#36]
In attempt to build a functioning app with ratchet, a number of edge cases have been encountered. This leads me to believe that we may need to rethink it's design.
## Overview

Fundamentally ratchet implements a protocol for binding data to HTML elements. There are only two places where data may be stored in an HTML document:
1. element attributes
2. element content
## Protocol

Previously, we had the concept of scopes and properties. A scope represented an area of concern, or domain, in the view. A scope might have a number of properties which data would be bound to. I propose we simplify this to just properties. Scopes are more or less a semantic which could be introduced later as a synonym for properties.

``` html
<!-- Previously -->
<article data-scope="post">
  <p data-prop="body"></p>
</article>

<!-- Now -->
<article data-prop="post">
  <p data-prop="body"></p>
</article>
```
## Edges

The following edge cases were encoutered while trying to translate existing apps with ratchet. These scenarios cannot be solved with the current version of ratchet (0.2.0).
### Case # 1

Updating only the attributes of an element. For e.g., you have an anchor tag with static text content. Only the `href` needs be bound when rendered.

``` html
<!-- Template -->
<a>Click here!</a>

<!-- Rendered -->
<a href="https://iamvery.com" rel="nofollow">Click here!</div>
```
### Case # 2

Updating attributes of an element as well as properties within its content. For e.g., you have a form tag that must have data bound to properties in its content as well as `action` and `method` attributes when rendered.

``` html
<!-- Template -->
<form>
  <input type="text">
  <button type="submit">Submit</button>
</form>

<!-- Rendered -->
<form action="..." method="post">
  <input type="text" name="full_name">
  <button type="submit">Submit</button>
</form>
```
### Case # 3

Currently there is no way to compose views from other files. For e.g., the application layout is in one file and the view specific to the particular page is in another file to be included. I'm on the fence whether this is really a responsibility of ratchet. On one hand, a claim of the lib is writing plain HTML views so that designers can easy prototype things. On the other hand, any including of external HTML breaks that whole idea anyway.

_At this time, I'm thinking we just shell out to EEx and call `render`._
### Case # 4

There may be a case where it is desirable to prepend/append content on an element rather than overwriting it. For e.g. a designer would have no reason to implement hidden form elements such as CSRF token as they do not affect the view.

``` html
<!-- Template -->
<form>
  <input type="text">
  <button type="submit">Submit</button>
</form>

<!-- Rendered -->
<form>
  <input type="hidden" name="csrf" value="...">
  <input type="text">
  <button type="submit">Submit</button>
</form>
```

_However, I don't think it's the responsibility of ratchet to generate to HTML content. IMO the developer should be able to retroactively add elements to the view and bind data to them as expected._
## Transformations

There are 5 transformations which may take place in the view.
1. Element content
2. Element attributes
3. Element content and attributes
4. Multiple elements (recursively applying 1-3 above)
5. Attributes and nested elements
### Element content

``` html
<!-- Template -->
<p data-prop="body"></p>

<!-- Rendered -->
<p data-prop="body">Content has been inserted</p>
```
### Element attributes

``` html
<!-- Template -->
<a data-prop="link">Click here!</a>

<!-- Rendered -->
<a href="https://iamvery.com" rel="nofollow" data-prop="link">Click here!</div>
```
### Element content and attributes

``` html
<!-- Template -->
<a data-prop="link"></div>

<!-- Rendered -->
<a href="https://iamvery.com" rel="nofollow" data-prop="link">iamvery</div>
```
### Multiple elements

``` html
<!-- Template -->
<article data-prop="post"></article>

<!-- Rendered -->
<article data-prop="post">...</article>
<article data-prop="post">...</article>
<article data-prop="post">...</article>
```
### Attributes and nested elements

``` html
<!-- Template -->
<form data-prop="new_comment">
  <input data-prop="body">
</form>

<!-- Rendered -->
<form action="/comments" method="post" data-prop="new_comment">
  <input name="comment[body]" data-prop="body">
</form>
```
## Data

As previously stated, there are two places for data in the view: content and attributes. Therefore there are two basic types of data: strings and keyword lists. These basic types may be combined into complex data structures to support complex views.

Consider the following prototype template for some posts with comments:

``` html
<article data-prop="posts">
  <h2>
    <a href="#" data-prop="title">Post Title</a>
  </h2>
  <p data-prop="body">Thoughts and opinions.</p>
  <a href="#" data-prop="permalink">Permalink</a>
  <ul>
    <li data-prop="comments">
      <span data-prop="user">Jay</span>
      <span data-prop="body">Yes and no</span>
    </li>
  </ul>
  <form data-prop="new_comment">
    <input data-prop="body">
    <button type="submit">New comment</button>
  </form>
</article>
```

When rendered with data, the final view would look like the following:

``` html
<article data-prop="posts">
  <h2><a href="/posts/1" data-prop="title">A good post</a></h2>
  <p data-prop="body">This post is about things.</p>
  <a href="/posts/1" data-prop="permalink">Permalink</a>
  <ul>
    <li data-prop="comments">
      <span data-prop="user">Jon</span>
      <span data-prop="body">Good read.</span>
    </li>
    <li data-prop="comments">
      <span data-prop="user">Les</span>
      <span data-prop="body">Can you even?</span>
    </li>
  </ul>
  <form action="/comments" method="post" data-prop="new_comment">
    <input name="comment[body]" data-prop="body">
    <button type="submit">New comment</button>
  </form>
</article>
```

The data:

``` elixir
data = [
  posts: [
    title: {"A good post", href: "/posts/1"},
    body: "This post is about things.",
    permalink: [href: "/posts/1"],
    comments: [
      [user: "Jon", body: "Good read."],
      [user: "Les", body: "Can you even?"],
    ],
    new_comment: {
      [body: [name: "comment[body]"]],
      action: "/comments", method: "post",
    }
  ]
]
```

Let's talk about the data...
#### String, e.g. post body

The body of the post is plain text content.

Data:

``` elixir
"This is the post body"
```

Applied:

``` html
<p data-prop="body">This is the post body</p>
```
#### Keyword List, e.g. post permalink

Only attributes need be bound on the permalink element. The keyword list has the general form `[attribute: value]`.

Data:

``` elixir
[href: "/posts/1"]
```

Applied:

``` html
<a href="/posts/1" data-prop="permalink">Permalink</a>
```
#### Tuple, e.g. post title

Both the content and attributes of the title are updated. The tuple has the general form `{content, attributes}`.

Data:

``` elixir
{"A good post", href: "/posts/1"}
```

Applied:

``` html
<a href="/posts/1" data-prop="title">A good post</a>
```
#### List, e.g. comments

A regular list is used as a collection of property data. The general form is `[data, ...]`

Data:

``` elixir
comments: [[...], [...]]
```

Applied:

``` html
<li data-prop="comments">...</li>
<li data-prop="comments">...</li>
```
#### Map, e.g. a post

Maps are used as a collection of properties to their data. They have the general form `%{property: data, ...}`

Data:

``` elixir
%{
  body: "...",
  permalink: [...],
  comments: [...],
  new_comment: {...},
}
```

Applied:

``` html
<article data-prop="post">...</article>
```
#### Combined concepts, e.g. new comment form

Both the content and attributes of the form must be updated, so a tuple is used. In this particular case, the content is recursively updated with additional properties.

Data:

``` elixir
{%{body: [name: "comment[body]"]}, action: "/comments", method: "post"}
```

Applied:

``` html
<form action="/comments" method="post" data-prop="new_comment">
  <input name="comment[body]" data-prop="body">
</form>
```
## EEx

An implementation detail of Ratchet is that it uses EEx as an intermediary format. Provided for example is the above template compiled to EEx:

``` html
<%= for post <- List.wrap(data.posts) do %>
  <article <%= Ratchet.Data.attributes(post, [{"data-prop", "posts"}]) %>>
    <%= if Ratchet.Data.content?(post) do %>
      <%= Ratchet.Data.content(post) %>
    <% else %>
      <h2>
        <%= for title <- List.wrap(post.title) do %>
          <a <%= Ratchet.Data.attributes(title, [{"href", "#"}, {"data-prop", "title"}]) %>>
            <%= if Ratchet.Data.content?(title) do %>
              <%= Ratchet.Data.content(title) %>
            <% else %>
              Post Title
            <% end %>
          </a>
        <% end %>
      </h2>
      <%= for body <- List.wrap(post.body) do %>
        <p <%= Ratchet.Data.attributes(body, [{"data-prop", "body"}]) %>>
          <%= if Ratchet.Data.content?(body) do %>
            <%= Ratchet.Data.content(body) %>
          <% else %>
            Thoughts and opinions.
          <% end %>
        </p>
      <% end %>
      <%= for permalink <- List.wrap(post.permalink) do %>
        <a <%= Ratchet.Data.attributes(permalink, [{"data-prop", "permalink"}]) %>>
          <%= if Ratchet.Data.content?(permalink) do %>
            <%= Ratchet.Data.content(permalink) %>
          <% else %>
            Permalink
          <% end %>
        </a>
      <% end %>
      <ul>
        <%= for comments <- List.wrap(post.comments) do %>
          <li <%= Ratchet.Data.attributes(comments, [{"data-prop", "comments"}]) %>>
            <%= if Ratchet.Data.content?(comments) do %>
              <%= Ratchet.Data.content(comments) %>
            <% else %>
              <%= for user <- List.wrap(comments.user) do %>
                <span <%= Ratchet.Data.attributes(user, [{"data-prop", "user"}]) %>>
                  <%= if Ratchet.Data.content?(user) do %>
                    <%= Ratchet.Data.content(user) %>
                  <% else %>
                    Jay
                  <% end %>
                </span>
              <% end %>
              <%= for body <- List.wrap(comments.body) do %>
                <span <%= Ratchet.Data.attributes(body, [{"data-prop", "body"}]) %>>
                  <%= if Ratchet.Data.content?(body) do %>
                    <%= Ratchet.Data.content(body) %>
                  <% else %>
                    Yes and no
                  <% end %>
                </span>
              <% end %>
            <% end %>
          </li>
        <% end %>
      </ul>
      <%= for new_comment <- List.wrap(post.new_comment) do %>
        <form <%= Ratchet.Data.attributes(new_comment, [{"data-prop", "new_comment"}]) %>>
          <%= if Ratchet.Data.content?(new_comment) do %>
            <%= Ratchet.Data.content(new_comment) %>
          <% else %>
            <%= for body <- List.wrap(new_comment.body) do %>
              <input <%= Ratchet.Data.attributes(body, [{"data-prop", "body"}]) %>>
            <% end %>
            <button type="submit">New comment</button>
          <% end %>
        </form>
      <% end %>
    <% end %>
  </article>
<%= end %>
```

(😱  WHAT HAVE I DONE)

**Comment by bryanp** [comment]
Following along. Can you explain the edge cases?

**Comment by iamvery** [comment]
Ya, I had to stop writing suddenly earlier. I still need to come back and finish this up 😅

**Comment by tessellator** [comment]
I haz opinions! 

If Lisp is a family of languages, then Pakyow is a family of like implementations. I'm trying to look at this from a generic Pakyow perspective, though I recognize that each implementation may have a slightly differing philosophy. All that to say: take the following with a grain of salt.

I disagree about replacing `data-scope` with `data-prop`. Personally, I think about a scope as providing selection semantics for the app developer, and I think of a prop as a binding primitive. It may be prudent to treat a scope as a _super_-prop, but I like the idea of being able to control binding with a little more granularity than at a view-global level. I guess I have control issues. :smiling_imp:

By `data-scope` being a super-prop, I mean that a scope is implicitly a prop unto itself. That sounds a little weird, so let me explain with an example. In glimpse (my Pakyow-family implementation), you can put `data-scope` and `data-prop` on the same element. Maybe you can in Pakyow, but I haven't tried it.

`<a data-scope="link_scope" data-prop="link_prop"></a>`
`(bind my-view :link-scope {:link-prop {:href "http://..." :content "..."}})`

I think this could be collapsed to the following:

`<a data-scope="link"></a>`
`(bind my-view :link {:href "http://..." :content "..."})`

This gives the scope all the same semantics as a prop, plus the ability to select it on the back-end as a target for `bind`. Recursive binding would work as normal. A view-global bind operation is then just a fold over the collection of scope-data pairs for a view.

This approach makes an assumption that I _think_ is wrong regarding your implementation, namely that the view is parsed into some data structure on the back-end and is rendered to HTML after binding occurs. However, I think this is a must-have if you want to support edge case 4. (You generate EEx from...the HTML views...and the binding is baked into the EEx? Sorry, I haven't looked at your code yet!) I do not understand what you mean by "the developer should be able to retroactively add elements to the view and bind data to them as expected." Does this mean adding elements to the HTML views, or manipulating the view at run-time, or ...?

Moving on, the data section sufficiently covers edge cases 1 and 2. Interestingly, I came up with almost exactly the same solution for glimpse, with the one exception being that instead of providing a bare value for content, I use the `:content` keyword (or atom in Elixir-speak) in the data map and treat it specially. Personally, I find the similarity encouraging.

Anyway, that's my $0.02. I'm really excited to play with Ratchet over the next week or so and look forward to seeing the direction in which you take it!

**Comment by bryanp** [comment]
Wanted to jump in and say that it is possible for a node to have both a scope and prop in Pakyow. Treating them as the same type of prop with different semantic meaning would not allow for this.

**Comment by tessellator** [comment]
> Wanted to jump in and say that it is possible for a node to have both a scope and prop in Pakyow. 

Sweet! Lazy web ftw!

> Treating them as the same type of prop with different semantic meaning would not allow for this.

Maybe I misunderstand your meaning, but I think this only true because of the design of the Pakyow API. In Pakyow (and glimpse), you select a named section of a view - a scope - to which you apply some data. But there are other approaches you could take. 

If you treat the entire view as a single scope (which I call a view-global scope), then you only need to select the uppermost prop nodes to start data application, like Ratchet. Or maybe you support some CSS selector syntax (I shudder at the thought of implementing that) that allows you to select one or more props. In either case, I think you can achieve the same effect without distinguishing between scope and prop, although both alternatives require that props be recursively definable.

**Comment by bryanp** [comment]
What I mean is without scopes you can't express a single node as both a binding point and a traversal. At least it isn't possible in Pakyow; perhaps it is in Glimpse or Ratchet.

``` html
<div data-scope="post" data-prop="body">
  <div data-scope="comment" data-prop="body"></div>
</div>
```

We can easily bind data to the post and comment scope (that also happen to represent parts of the data):

``` ruby
data = [{ body: 'p_one', comment: [{ body: 'c_one' }] }]
view.scope(:post).bindr(data)
```

How would you do this without scopes?

**Comment by iamvery** [comment]
> I disagree about replacing data-scope with data-prop. Personally, I think about a scope as providing selection semantics for the app developer, and I think of a prop as a binding primitive. It may be prudent to treat a scope as a super-prop, but I like the idea of being able to control binding with a little more granularity than at a view-global level.

The reason behind this decision in Ratchet may not have translated well in this issue. At this point in the lib's existence, there is no difference at all in scope and prop. So in attempt to simplify the implementation scope is ditched until there is a reason for it to exist.

In pakyow (and perhaps glimpse), scope is a necessary structure for identifying a point in which to bind data. For better or worse, this is not needed in Ratchet. It is assumed that you will "pass the world to the view". That means instead of binding bits and pieces as the view is built up, you create the entire set of data needed for the view and finally show it at the end. This actually feel very FP to me. Along the same lines of Phoenix/Plug piping a Conn structure through all manner of functions before finally using it to respond to a request.

A lot of this is theoretical because I haven't yet implemented any of the data niceties in ratchet, but I'm imagining a sort of data pipeline that culminates in the final view. Maybe something like

``` elixir
data
|> add(:articles, articles_collection)
|> add(:new_comment_form, comment_form_data)
|> render("index.html")
```

I literally spit that example out on the spot, so no idea if there's any legitimacy to the API, but the idea is to give the use some interface for building up the data so that you don't have to write all the maps and such by hand.

**Comment by iamvery** [comment]
> How would you do this without scopes?

In ratchet the data informs the view. So if you wanted to add attributes to an element and update internal properties, you'd have a template and data like the following:

``` html
<div data-prop="foo">
  <p data-prop="bar"></p>
</div>
```

``` elixir
data = %{
  foo: {%{bar: "Some bar content"}, class: "foo-class"}
}
```

would result in the view:

``` html
<div class="foo-class" data-prop="foo">
  <p data-prop="bar">Some bar content</p>
</div>
```

**Comment by iamvery** [comment]
This is addressed by #38, #39, and #40. I'll go ahead and close the issue, but we can still discuss 😄

**Comment by bryanp** [comment]
Can you show an example of setting content on both foo and bar?

**Comment by tessellator** [comment]
> That means instead of binding bits and pieces as the view is built up, you create the entire set of data needed for the view and finally show it at the end.

I see what you mean; I guess I just think about it differently. I like to think of the view as data against which you perform a series of transformations, the result of each transform usually being a new view with rendering being the notable exception. Bind and render are the two most prominent transforms, but others can be defined to do whatever you want (e.g., inserting a CSRF token into a form and adding it to a session, modifying the page title). Building up the data to bind is an independent activity, and binding the data can happen either piecewise or one-shot.

That being said, I think your suggested approach will work well. The arguments I'm making are primarily philosophical; the effects are the same either way. So in the end, we all win. :smiley:

The one edge that I see is actually sort of presented in Bryan's sample. What happens if you bind element content into a prop that has children props? Personally, I think this should be disallowed so you don't overwrite existing content underneath the prop, but I can see an argument for deleting or appending to the existing content as well. (And it appears Bryan beat me to the punch...)

**Comment by iamvery** [comment]
@bryanp the ratchet philosophy doesn't even match this thinking presently. i.e. the content of a node is either provided as data or defined in the view itself. Therefore if content data is present the view content is replaced. After our pairing today, I realize how this seems to diverge pretty significantly from Pakyow. I think I need to feel it hurt before I decide if they're mistakes.

@tessellator I'm likely reaching a tipping point where I decide if my design if flawed, oversimplified, etc. A lot of it is presently influenced by my dependency on EEx for template compilation. It may be that EEx is not "smart" enough to really pull off view transformation. I'd really like to talk to you more about your implementation. Might you be willing to give me a tour? (idk clojure at all..)

**Comment by tessellator** [comment]
Sure! I'll drop you a line so we can set something up.

**Comment by bryanp** [comment]
@tessellator Something I mentioned to @iamvery when pairing today was that I see a fundamental difference between content and structure. In the example below, "foo" is content of the scope while the nested div is simply more structure.

``` html
<div data-scope="foo">
  foo
  <div></div>
</div>
```

In Pakyow we decided that inserting a value into a node should only replace content, never the structure contained within it. Structural changes happen via other parts of the transformation api.

**Comment by tessellator** [comment]
Ah, that's interesting. I need to think about that a bit. Might have questions later.
